from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
import numpy as np

TRAINING_DATA = [
    # Class 1 — Lý do recommendation (26 mẫu)
    ("Tại sao khóa học này được gợi ý cho tôi?", "reason"),
    ("Vì sao tôi nên học khóa này?", "reason"),
    ("Lý do nào khiến hệ thống chọn khóa học này?", "reason"),
    ("Tại sao đây là khóa học phù hợp với tôi?", "reason"),
    ("Hệ thống dựa vào đâu để gợi ý khóa này?", "reason"),
    ("Why was this course recommended to me?", "reason"),
    ("What is the reason for this recommendation?", "reason"),
    ("Why should I take this course specifically?", "reason"),
    ("How did the system decide to recommend this?", "reason"),
    ("What made the system suggest this course?", "reason"),
    ("Tôi không hiểu tại sao khóa này phù hợp với tôi", "reason"),
    ("Cơ sở nào để gợi ý khóa học này?", "reason"),
    ("Khóa này được đề xuất dựa trên tiêu chí gì?", "reason"),
    ("Giải thích cho tôi tại sao tôi cần học khóa này", "reason"),
    ("Tại sao đây là bước tiếp theo trong lộ trình của tôi?", "reason"),
    ("What criteria were used to recommend this?", "reason"),
    ("Can you explain why this was suggested?", "reason"),
    ("I don't understand why this course is for me", "reason"),
    ("What is the justification for this recommendation?", "reason"),
    ("Why this course and not another one?", "reason"),
    ("Hệ thống gợi ý này hoạt động thế nào với tôi?", "reason"),
    ("Tại sao không gợi ý khóa khác cho tôi?", "reason"),
    ("Lý do cụ thể để tôi chọn khóa học này là gì?", "reason"),
    ("Recommendation này có phù hợp với mục tiêu của tôi không?", "reason"),
    ("Giải thích lý do recommendation", "reason"),
    ("Tôi muốn biết lý do được recommend khóa này", "reason"),

    # Class 2 — Nội dung trên trang recommendation (26 mẫu)
    ("Nội dung khóa học này gồm những gì?", "content"),
    ("Khóa học bao gồm những chủ đề nào?", "content"),
    ("Tôi sẽ học được những gì trong khóa này?", "content"),
    ("Mô tả khóa học này cho tôi?", "content"),
    ("Chương trình học của khóa này như thế nào?", "content"),
    ("What does this course cover?", "content"),
    ("What topics are included in this course?", "content"),
    ("Describe the content of this course", "content"),
    ("What will I study in this course?", "content"),
    ("Give me an overview of the course content", "content"),
    ("Các module trong khóa học là gì?", "content"),
    ("Syllabus của khóa học này?", "content"),
    ("Khóa học có bao nhiêu chương?", "content"),
    ("Nội dung chi tiết của khóa học?", "content"),
    ("Khóa học này dạy những gì?", "content"),
    ("What are the modules in this course?", "content"),
    ("How is the course structured?", "content"),
    ("What is the syllabus?", "content"),
    ("Tell me about the course content", "content"),
    ("What subjects does this course teach?", "content"),
    ("Trang recommendation hiển thị thông tin gì?", "content"),
    ("Giải thích những mục được hiển thị trong lộ trình", "content"),
    ("Các phần học trong khóa này là gì?", "content"),
    ("Khóa học gồm bao nhiêu phần?", "content"),
    ("Tổng quan nội dung khóa học", "content"),
    ("Course overview là gì?", "content"),

    # Class 3 — Lợi ích khi học (26 mẫu)
    ("Học khóa này tôi được lợi ích gì?", "benefit"),
    ("Sau khi học xong tôi có thể làm được gì?", "benefit"),
    ("Tại sao tôi nên đầu tư thời gian cho khóa này?", "benefit"),
    ("Khóa học này giúp ích gì cho sự nghiệp của tôi?", "benefit"),
    ("Lợi ích của việc học khóa này là gì?", "benefit"),
    ("What are the benefits of this course?", "benefit"),
    ("What skills will I gain from this course?", "benefit"),
    ("How will this course help my career?", "benefit"),
    ("What can I do after completing this course?", "benefit"),
    ("Why is this course valuable?", "benefit"),
    ("Kỹ năng nào tôi sẽ có sau khóa học?", "benefit"),
    ("Khóa học có giúp tôi tìm việc không?", "benefit"),
    ("Giá trị thực tế của khóa học này?", "benefit"),
    ("Tôi sẽ giỏi hơn điều gì sau khi học?", "benefit"),
    ("Học xong khóa này tôi được gì?", "benefit"),
    ("What practical skills does this give me?", "benefit"),
    ("Is this course worth my time?", "benefit"),
    ("How does this course benefit me professionally?", "benefit"),
    ("What outcomes can I expect?", "benefit"),
    ("Will this course improve my job prospects?", "benefit"),
    ("Lợi ích ngắn hạn và dài hạn của khóa học?", "benefit"),
    ("Khóa học mang lại giá trị gì cho tôi?", "benefit"),
    ("Tôi học được kỹ năng thực tế nào?", "benefit"),
    ("Outcome của khóa học là gì?", "benefit"),
    ("Điểm mạnh của khóa học này so với tự học?", "benefit"),
    ("Học khóa này có giúp tôi thăng tiến không?", "benefit"),

    # Class 4 — Quan hệ với các khóa khác trong KG (26 mẫu)
    ("Khóa học này liên quan đến những khóa nào khác?", "relation"),
    ("Khóa học này tương tự khóa nào?", "relation"),
    ("Có khóa học nào kết nối với khóa này không?", "relation"),
    ("Mối quan hệ giữa khóa này và các khóa khác?", "relation"),
    ("Khóa này khác gì so với khóa data visualization?", "relation"),
    ("What courses are related to this one?", "relation"),
    ("Which courses are similar to this?", "relation"),
    ("How does this course connect to others?", "relation"),
    ("What is the relationship between this and other courses?", "relation"),
    ("Are there similar courses I should know about?", "relation"),
    ("Khóa học này thuộc nhóm nào trong hệ thống?", "relation"),
    ("Những khóa nào bổ trợ cho khóa này?", "relation"),
    ("So sánh khóa này với machine learning", "relation"),
    ("Điểm khác biệt giữa khóa này và khóa khác?", "relation"),
    ("Khóa học này có liên kết với domain nào?", "relation"),
    ("What courses complement this one?", "relation"),
    ("How similar is this to machine learning?", "relation"),
    ("What are the differences between this and other courses?", "relation"),
    ("Which domain does this course belong to?", "relation"),
    ("What courses share topics with this one?", "relation"),
    ("Tìm khóa học tương tự trong hệ thống", "relation"),
    ("Khóa học này có kết nối với lĩnh vực health không?", "relation"),
    ("Mức độ liên quan của khóa này với data science?", "relation"),
    ("Những khóa học nào có similarity cao với khóa này?", "relation"),
    ("So sánh nội dung khóa này với khóa Python", "relation"),
    ("Khóa học này được xếp vào cộng đồng nào trong KG?", "relation"),

    # Class 5 — Thông tin thêm về tài liệu (26 mẫu)
    ("Cho tôi biết thêm thông tin về khóa học này", "info"),
    ("Chi tiết về khóa học?", "info"),
    ("Khóa học kéo dài bao lâu?", "info"),
    ("Ai dạy khóa học này?", "info"),
    ("Độ khó của khóa học này thế nào?", "info"),
    ("Tell me more about this course", "info"),
    ("What is the difficulty level?", "info"),
    ("How long does this course take?", "info"),
    ("Who teaches this course?", "info"),
    ("Give me more details about this course", "info"),
    ("Cần điều kiện gì để học khóa này?", "info"),
    ("Khóa học này có chứng chỉ không?", "info"),
    ("Giờ học của khóa này là bao nhiêu?", "info"),
    ("Khóa học được đánh giá như thế nào?", "info"),
    ("Metadata của khóa học này là gì?", "info"),
    ("What are the prerequisites?", "info"),
    ("Does this course have a certificate?", "info"),
    ("How many hours is this course?", "info"),
    ("What is the course rating?", "info"),
    ("What format is this course in?", "info"),
    ("Thông tin cơ bản về khóa học?", "info"),
    ("Mô tả ngắn gọn về khóa học", "info"),
    ("Khóa học này ở level nào?", "info"),
    ("Tôi cần biết thêm về tài liệu học", "info"),
    ("Thông tin chi tiết về learning material", "info"),
    ("Khóa học này phù hợp với ai?", "info"),

    # Class 6 — Liên quan đến công việc hàng ngày (26 mẫu)
    ("Khóa học này áp dụng được gì vào công việc của tôi?", "context"),
    ("Tôi làm data engineer, khóa này có phù hợp không?", "context"),
    ("Trong dự án hiện tại tôi có dùng được kiến thức này không?", "context"),
    ("Khóa học có liên quan đến công việc thực tế không?", "context"),
    ("Tôi đang làm về healthcare, khóa này giúp gì?", "context"),
    ("How does this relate to my daily work?", "context"),
    ("I work as a developer, is this relevant?", "context"),
    ("Can I apply this to my current project?", "context"),
    ("How is this useful for my job?", "context"),
    ("I work in healthcare, how does this help me?", "context"),
    ("Ứng dụng thực tế của khóa học trong ngành của tôi?", "context"),
    ("Tôi là kỹ sư phần mềm, học khóa này làm gì?", "context"),
    ("Kiến thức này dùng được trong môi trường làm việc không?", "context"),
    ("Khóa học có relevance với vị trí của tôi không?", "context"),
    ("Tôi làm analyst, khóa này có giúp tôi không?", "context"),
    ("As a project manager, is this useful?", "context"),
    ("Will this help me in my current role?", "context"),
    ("I'm a student, how does this fit my goals?", "context"),
    ("How does this align with my career path?", "context"),
    ("Can I use this knowledge at work tomorrow?", "context"),
    ("Liên hệ giữa khóa học và công việc thực tế?", "context"),
    ("Tôi làm việc về AI, khóa này có cần thiết không?", "context"),
    ("Ngành của tôi có cần kỹ năng này không?", "context"),
    ("Khóa học này phù hợp với career goal của tôi?", "context"),
    ("Trong team của tôi ai nên học khóa này?", "context"),
    ("Tôi có nên ưu tiên học khóa này trong lịch làm việc?", "context"),

    # Class 7 — Other (26 mẫu)
    ("Hôm nay thời tiết thế nào?", "other"),
    ("Bạn là ai?", "other"),
    ("Kể cho tôi nghe một câu chuyện cười", "other"),
    ("Giá Bitcoin hôm nay là bao nhiêu?", "other"),
    ("Tôi muốn đặt pizza", "other"),
    ("What is the weather today?", "other"),
    ("Tell me a joke", "other"),
    ("Who are you?", "other"),
    ("What is the meaning of life?", "other"),
    ("Can you help me with my homework?", "other"),
    ("Cho tôi công thức nấu phở", "other"),
    ("Bóng đá tối nay có trận nào không?", "other"),
    ("Tôi muốn chat với bạn bè", "other"),
    ("Dịch đoạn văn này sang tiếng Anh", "other"),
    ("Viết code Python cho tôi", "other"),
    ("What time is it?", "other"),
    ("Help me write an email", "other"),
    ("What movies are playing tonight?", "other"),
    ("I want to complain about something", "other"),
    ("Book me a flight ticket", "other"),
    ("Nhiệt độ nước sôi là bao nhiêu?", "other"),
    ("Tôi cần tư vấn tâm lý", "other"),
    ("Giải thích công thức toán học này", "other"),
    ("Tôi muốn học ngoại ngữ", "other"),
    ("Chơi game với tôi", "other"),
    ("Kết bạn với tôi nhé", "other"),
]

texts  = [t for t, _ in TRAINING_DATA]
labels = [l for _, l in TRAINING_DATA]

pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1)),
    ("clf",   LinearSVC(C=1.0, max_iter=2000)),
])
pipeline.fit(texts, labels)

def classify_intent(text: str) -> str:
    return pipeline.predict([text])[0]
